"""
Merge per-page MLLM tag outputs into a single combined JSON file.

After you send each page image to the MLLM and save its JSON response as
playground/page_N_tags.json, this script merges them into one file that
the inject step can consume.

It also converts normalized bboxes [0-1] to PDF page coordinates using
the pages_meta.json generated by render_pages.py.

Usage:
    python merge_outputs.py                                       # Auto-find from playground/
    python merge_outputs.py --input-dir playground --output merged_tags.json
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PLAYGROUND_DIR = SCRIPT_DIR / "playground"
DEFAULT_OUTPUT = SCRIPT_DIR / "merged_tags.json"


def normalized_to_pdf(bbox_norm: list[float], pdf_width: float, pdf_height: float) -> list[float]:
    """Convert normalized [0,1] bounding box to PDF points (top-left origin)."""
    # Auto-detect Gemini [0, 1000] scale fallback
    if any(v > 1.0 for v in bbox_norm):
        bbox_norm = [v / 1000.0 for v in bbox_norm]
        
    return [
        round(bbox_norm[0] * pdf_width, 2),
        round(bbox_norm[1] * pdf_height, 2),
        round(bbox_norm[2] * pdf_width, 2),
        round(bbox_norm[3] * pdf_height, 2),
    ]


def merge_page_outputs(input_dir: Path, output_path: Path) -> dict:
    """Merge all page_N_tags.json files into one combined output.

    Returns the merged data dict.
    """
    # Load page metadata for coordinate conversion
    meta_path = input_dir / "pages_meta.json"
    if not meta_path.is_file():
        print(f"Warning: {meta_path} not found — coordinate conversion will be skipped.")
        pages_meta = None
    else:
        with open(meta_path, "r", encoding="utf-8") as f:
            pages_meta = json.load(f)

    # Build a page_idx -> page_info lookup
    page_info_map = {}
    if pages_meta:
        for p in pages_meta.get("pages", []):
            page_info_map[p["page_idx"]] = p

    # Find all page_N_tags.json files
    tag_files = sorted(
        input_dir.glob("page_*_tags.json"),
        key=lambda f: int(re.search(r"page_(\d+)_tags", f.name).group(1))
    )

    if not tag_files:
        print(f"Error: No page_*_tags.json files found in {input_dir}")
        sys.exit(1)

    all_elements = []
    all_page_results = []
    final_tracking = None
    errors = 0

    for tag_file in tag_files:
        page_match = re.search(r"page_(\d+)_tags", tag_file.name)
        page_idx = int(page_match.group(1))

        with open(tag_file, "r", encoding="utf-8") as f:
            page_data = json.load(f)

        # Handle error pages
        if "error" in page_data:
            print(f"  [!] Page {page_idx}: skipped (had error: {page_data['error']})")
            errors += 1
            all_page_results.append(page_data)
            continue

        elements = page_data.get("elements", [])
        page_info = page_info_map.get(page_idx)

        # Convert normalized bboxes to PDF coordinates
        for elem in elements:
            elem["page_idx"] = page_idx  # stamp page index on each element

            if "bbox" in elem and elem["bbox"] and page_info:
                b = elem["bbox"]
                # Prompt strictly enforces [ymin, xmin, ymax, xmax] on a 1000x1000 scale
                b = [b[1]/1000.0, b[0]/1000.0, b[3]/1000.0, b[2]/1000.0]
                
                elem["bbox_normalized"] = list(b)
                elem["bbox"] = normalized_to_pdf(
                    b,
                    page_info["pdf_width"],
                    page_info["pdf_height"],
                )

            all_elements.append(elem)

        # Keep the latest tracking state
        tracking = page_data.get("updated_tracking")
        if tracking:
            final_tracking = tracking

        all_page_results.append(page_data)
        print(f"  Page {page_idx}: {len(elements)} elements")

    # Build merged output
    merged = {
        "pdf": pages_meta.get("pdf", "unknown") if pages_meta else "unknown",
        "total_pages": pages_meta.get("total_pages", 0) if pages_meta else 0,
        "pages_processed": [int(re.search(r"page_(\d+)_tags", f.name).group(1)) for f in tag_files],
        "total_elements": len(all_elements),
        "elements": all_elements,
        "final_tracking": final_tracking,
        "per_page_results": all_page_results,
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(merged, f, indent=2)

    return merged


def main():
    parser = argparse.ArgumentParser(description="Merge per-page MLLM tag outputs")
    parser.add_argument("--input-dir", default=str(PLAYGROUND_DIR),
                        help=f"Dir with page_N_tags.json files (default: {PLAYGROUND_DIR})")
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUTPUT),
                        help=f"Output merged JSON (default: {DEFAULT_OUTPUT})")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_path = Path(args.output)

    if not input_dir.is_dir():
        print(f"Error: Input directory not found: {input_dir}")
        return 1

    print(f"Merging page outputs from: {input_dir}")
    merged = merge_page_outputs(input_dir, output_path)

    print(f"\n  Done!")
    print(f"  Total elements: {merged['total_elements']}")
    print(f"  Pages merged: {len(merged['pages_processed'])}")
    print(f"  Output: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
